version: '3.8'
services:

  nexus3:
    # credentials can be fetched from command line: docker exec -it nexus cat /nexus-data/admin.password
    build:
      context: ./nexus
    image: bensimpson-ch/nexus3:latest
    container_name: nexus
    volumes:
      - nexus-data:/nexus-data
    ports:
      - 8081:8081

  # ERROR: [1] bootstrap checks failed. You must address the points described in the following [1] lines before starting Elasticsearch.
  # bootstrap check failure [1] of [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]

  # edit your configuration: sudo vi /etc/sysctl.conf
  # add at the bottom: vm.max_map_count=262144
  # reload your changes: sudo sysctl -p

  # documentation: https://docs.sonarsource.com/sonarqube/latest/setup-and-upgrade/install-the-server/installing-sonarqube-from-docker/

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    restart: always
    depends_on:
      - sonarqube-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-logs:/opt/sonarqube/log
    ports:
      - 9000:9000

  #documentation: https://hub.docker.com/_/postgres
  sonarqube-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - sonarqube-db-pgdata:/var/lib/postgresql/data

volumes:
  nexus-data:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:
  sonarqube-db-pgdata: